// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfxeoyfxjbljgvjvjfhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmeGVveWZ4amJsamd2anZqZmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MjA0NjIsImV4cCI6MjA1NTI5NjQ2Mn0.ZFux4vm8BbSHR2MY7kh98SPdJme6pkDPamZ7PzfL2qU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);